services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blinks1234
      MYSQL_DATABASE: test
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: blinks123
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    restart: always
    ports:
      - "8000"
    expose:
      - 8000
    depends_on:
      - mysql
    environment:
      WAITING_ROOM_API_URL: "https://d222kaz4akmu65.cloudfront.net"
      WAITING_ROOM_EVENT_ID: "Sample"
      ISSUER: "https://rqs7esknt7.execute-api.eu-west-2.amazonaws.com/api"
      DB_USER: "fastapi"
      DB_PASSWORD: "blinks123"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_NAME: "test"

volumes:
  mysql_data:
