services:
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blinks1234
      MYSQL_DATABASE: test
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: blinks123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
